# application.yml
spring:
    profiles:
        active: hash # allowed values are hash, grep, sql (sql is experimental only)

---

spring:
    config:
        activate:
            on-profile: sql
    datasource:
        url: jdbc:postgresql://localhost:5432/topwords
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver

---

spring:
    config:
        activate:
            on-profile: hash,grep
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration




